### ISSUE TITLE
Add a "documentation-only" type along the lines of Enumerable.t(_element)

### ISSUE THREAD

**Issue by jzimbel-mbta** [Qqwy/elixir-arrays#93]
Hello, love this library! As a nice-to-have for expressive typespecs, I would like to have an `Arrays.array(_element)` type. This would be effectively the same as `Arrays.array()`—that is, the element type parameter would just get thrown out. So it would make no difference to Dialyzer etc, but would be helpful for humans reading the code.

This same "documentation-only" type was recently added to `Enumerable`, [relevant code here](https://github.com/elixir-lang/elixir/blob/v1.15.4/lib/elixir/lib/enum.ex#L40-L55).

**Comment by Qqwy** [comment]
Thank you very much! This is a great suggestion.

I'm a bit indisposed the rest of today; I'll have a look at your PR tomorrow :-)
